### ISSUE TITLE
hello, some questions about data preparation and convergence during the training process.

### ISSUE THREAD

**Issue by dgo2dance** [Joe-2002/LinChance-Fine-tuning-System#1]
In the data file 'lima.json,' the 'input' and 'output' fields have values, the 'instruction' field is empty. However, in other datasets provided by the Llama Factory, the 'instruction' and 'output' fields have values, while the 'input' field is empty. Can explain how the data should be prepared

Also, when using datasets provided by the Llama Factory, such as oaast_sft_zh.json, the training process does not converge. Is there any help

**Comment by Joe-2002** [comment]
Our fine-tuning is based on the LlaMa Factory, so as long as the data follows the supported format of the LlaMa Factory, it should suffice. Additionally, in the lima dataset, our sample data is tailored to our needs. You have the option to enhance fine-tuning by providing prompt settings in the instruction or leaving it empty. Alternatively, you can give prompt cues in the input. For now, please adhere to the format reference provided in our lima dataset, and if you wish to upload a custom format dataset, replace the dataset name with "lima" (hash values are required in LlaMa Factory to match datasets), and remove the original dataset.
